#!/bin/bash
# Path to the JAR file
JAR_PATH="./target/command-line-tool-kotlin-1.0-SNAPSHOT.jar"

# Check if the JAR file exists
if [[ ! -f "$JAR_PATH" ]]; then
  echo "Error: JAR file not found at $JAR_PATH"
  exit 1
fi

# Run the JAR file
java -jar "$JAR_PATH" "$@"
